version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
      # ports:
      #- 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - type: bind
        source: ./wp_so
        target: /var/www/html
#        - wordpress: /var/www/html
    networks:
      - app-network

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - type: bind
        source: ./wp_db
        target: /var/lib/mysql
#      - db:/var/lib/mysql
    networks:
      - app-network

  proxy:
    depends_on:
      - wordpress
    image: nginx
    container_name: proxy
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - wordpress:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d


volumes:
  wordpress:
  db:

networks:
  app-network:
    driver: bridge
